name: standard-ci

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - demo
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
        - 27017:27017

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: yarn install --immutable

    - name: Build
      run: yarn build

    - name: Test
      run: yarn mocha

    - name: Lint
      run: yarn lint
